[package]
name = "twitchctl"
version = "0.1.0"
authors = ["Togglebit <me@togglebit.io>", "_Bare <bare@logixsr.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
